### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by VergLsm** [fbradyirl/openwrt-luci-rpc#33]
* openwrt-luci-rpc version: 
* Python version: 3.7.5
* Operating System: openwrt

### Description

Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/homeassistant/components/device_tracker/setup.py", line 164, in async_device_tracker_scan
    found_devices = await scanner.async_scan_devices()
  File "/thread.py", line 57, in run
  File "/opt/venv/lib/python3.7/site-packages/homeassistant/components/luci/device_tracker.py", line 63, in scan_devices
    self._update_info()
  File "/opt/venv/lib/python3.7/site-packages/homeassistant/components/luci/device_tracker.py", line 91, in _update_info
    result = self.router.get_all_connected_devices(only_reachable=True)
  File "/opt/venv/lib/python3.7/site-packages/openwrt_luci_rpc/__init__.py", line 43, in get_all_connected_devices
    only_reachable=only_reachable, wlan_interfaces=wlan_interfaces)
  File "/opt/venv/lib/python3.7/site-packages/openwrt_luci_rpc/openwrt_luci_rpc.py", line 169, in get_all_connected_devices
    device_entry = utilities.normalise_keys(device_entry)
  File "/opt/venv/lib/python3.7/site-packages/openwrt_luci_rpc/utilities.py", line 13, in normalise_keys
    {k.replace(".", "_").replace(" ", "_"): v for k, v in result.items()}
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by timstanley1985** [comment]
Hi, I have been getting this in my logs multiple times a day for months too

**Comment by fbradyirl** [comment]
Fixed in v1.1.6 https://github.com/fbradyirl/openwrt-luci-rpc/compare/v1.1.5...v1.1.6
