### ISSUE TITLE
Not working with OpenWRT Snapshot version

### ISSUE THREAD

**Issue by jacekpaszkowski** [fbradyirl/openwrt-luci-rpc#35]
* openwrt-luci-rpc version: latest
* Python version: 3.7
* Operating System: HassOs

### Description

Getting device list not working with Snapshot version of OpenWRT (OpenWrt SNAPSHOT r11869-a176f8d3ec)

### What I Did
I use Hass.io.
```
2020-01-01 20:57:35 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/openwrt_luci_rpc/openwrt_luci_rpc.py", line 215, in _call_json_rpc
    content = result['result']
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/setup.py", line 164, in async_device_tracker_scan
    found_devices = await scanner.async_scan_devices()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/luci/device_tracker.py", line 63, in scan_devices
    self._update_info()
  File "/usr/src/homeassistant/homeassistant/components/luci/device_tracker.py", line 91, in _update_info
    result = self.router.get_all_connected_devices(only_reachable=True)
  File "/usr/local/lib/python3.7/site-packages/openwrt_luci_rpc/__init__.py", line 43, in get_all_connected_devices
    only_reachable=only_reachable, wlan_interfaces=wlan_interfaces)
  File "/usr/local/lib/python3.7/site-packages/openwrt_luci_rpc/openwrt_luci_rpc.py", line 161, in get_all_connected_devices
    arp_result = self._call_json_rpc(*self.arp_call)
  File "/usr/local/lib/python3.7/site-packages/openwrt_luci_rpc/openwrt_luci_rpc.py", line 237, in _call_json_rpc
    raise LuciRpcUnknownError("No result in response from luci")
```
Also when i try to call api manually ({"method": "neighbors", "params": ["family": 4]}) i get:
{
"id": null,
"error": {
"message": "Parse error.",
"code": -32700
},
"jsonrpc": "2.0"
}

**Comment by jacekpaszkowski** [comment]
Fixed https://github.com/openwrt/luci/issues/3470
