### ISSUE TITLE
LuciRpcMethodNotFoundError in Home Assistant luci integration 

### ISSUE THREAD

**Issue by fangly** [fbradyirl/openwrt-luci-rpc#52]
* openwrt-luci-rpc version: git-22.052.50988-1b6c126-1
* Python version: 3.7.12
* Operating System: Linux turris 4.14.269 #0 SMP Mon Mar 7 07:26:07 2022 armv7l GNU/Linux

### Description

I have freshly installed luci-mod-rpc on my Turris Omnia router to enable presence detection in Home Assistant via its [luci integration](https://www.home-assistant.io/integrations/luci/).

### What I Did

After setting up the luci integration and restarting Home Assistant, the Home Assistant log shows:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 353, in async_device_tracker_scan
    found_devices = await scanner.async_scan_devices()
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 827, in async_scan_devices
    return await self.hass.async_add_executor_job(self.scan_devices)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/luci/device_tracker.py", line 67, in scan_devices
    self._update_info()
  File "/usr/src/homeassistant/homeassistant/components/luci/device_tracker.py", line 95, in _update_info
    result = self.router.get_all_connected_devices(only_reachable=True)
  File "/usr/local/lib/python3.9/site-packages/openwrt_luci_rpc/__init__.py", line 42, in get_all_connected_devices
    return self.router.get_all_connected_devices(
  File "/usr/local/lib/python3.9/site-packages/openwrt_luci_rpc/openwrt_luci_rpc.py", line 161, in get_all_connected_devices
    arp_result = self._call_json_rpc(*self.arp_call)
  File "/usr/local/lib/python3.9/site-packages/openwrt_luci_rpc/openwrt_luci_rpc.py", line 229, in _call_json_rpc
    raise LuciRpcMethodNotFoundError(
openwrt_luci_rpc.exceptions.LuciRpcMethodNotFoundError: ("method: '%s' returned an error '%s' (code: '%s).", 'net.arptable', 'Method not found.', -32601)
```

I am not familiar enough with the software to determine if the issue resides in the luci integration or openwrt-luci-rpc...

**Comment by fangly** [comment]
I did more reading and it seems like my issue is a duplicate of #30.

**Comment by fangly** [comment]
> Turris OS 5.3 is based on top of OpenWrt 19.07

Despite this, the reported VERSION_ID is "5.3.6".

**Comment by motolav** [comment]
Since OpenWrt 19.07 is EOL it'd probably be easier just to deprecate the legacy method if the backwards compatibility isn't required as there's no legacy required version that'd get software updates outside of third party repos and forks

**Comment by r4ym0n** [comment]
Just try to modify `/etc/os-release`. set the VERSION_ID to 18.06
```
VERSION_ID="18.06"
```
it works for me. XD

**Comment by DOFfactory** [comment]
any news on this?

**Comment by Poci** [comment]
Any news? Still waiting for this.
